# Site
repository: minemanemo/minemanemo.github.io
favicon: https://github.githubassets.com/favicons/favicon-dark.png

# Content configuration version
version: 2

# Personal info
name: ì´ë¯¼íšŒ
title: Front-end Engineer
email_title: Email
email: minhoe1122@gmail.com
# phone_title: Phone (Phone title override)
# phone: Your phone number (optional)
# website_title: RoketPunch
# website: https://rocketpunch.com/@minhoe1122

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: jekyllrb
github_username: minemanemo
tistory_username: minemanemo
rocketpunch_username: minhoe1122
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: people/ì´ë¯¼íšŒ/100003013980481/
# flickr_username: jekyll
instagram_username: minoi1122
linkedin_username: ë¯¼íšŒ-ì´-965b68211
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://avatars.githubusercontent.com/u/49668613?v=4
about_content: |
  "I can do anything, but I cannot do everything"

  ëª¨ë“ ê±¸ ë‹¤ í•  ìˆ˜ëŠ” ì—†ì§€ë§Œ ë¬´ì—‡ì´ë“  í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.

  ë°°ì›€ì˜ ìš•ì‹¬, ë°°ì›€ì— ëŒ€í•œ ì‹¤í˜„, ì§€ì‹ì˜ ë‚˜ëˆ”ê³¼ í˜‘ì—…ì„ ëª©í‘œë¡œ í•˜ëŠ” ê°œë°œì ì…ë‹ˆë‹¤.

  <hr />

  `Front-End ê°œë°œì„ ì¢‹ì•„í•©ë‹ˆë‹¤.`

  - ì‚¬ìš©ì ê²½í—˜ ì¦ëŒ€ì— ë³´ë‹¤ ì•ì¥ ì„¤ ìˆ˜ ìˆëŠ” ì ì— ë§¤ë ¥ì„ ëŠê»´ Front-End ê°œë°œìë¥¼ ì‹œì‘í•˜ê²Œ ë˜ì—ˆìŠµë‹ˆë‹¤.
  - ì‚¬ìš©ì ì…ì¥ì„ ê³ ë ¤í•˜ê³  ë””ìì´ë„ˆì™€ ì†Œí†µí•˜ë©° ë³´ë‹¤ ì¢‹ì€ ì‚¬ìš©ì ê²½í—˜ì„ ëŒì–´ë‚´ë ¤ê³  ë…¸ë ¥í•©ë‹ˆë‹¤.
  - í•­ìƒ ìƒˆë¡œìš´ ê²ƒì„ ê³µë¶€í•˜ë©° ì¢‹ì€ ì„œë¹„ìŠ¤ë¥¼ ê°œë°œí•˜ê¸° ìœ„í•´ ë…¸ë ¥í•©ë‹ˆë‹¤.

  `ë ˆê±°ì‹œ ì‹œìŠ¤í…œì´ ë‘ë µì§€ ì•ŠìŠµë‹ˆë‹¤.`

  - APM(Apache, PHP, MySQL) ê¸°ë°˜ì˜ ë ˆê±°ì‹œ ì›¹ ì„œë¹„ìŠ¤ ìš´ì˜ ê²½í—˜
  - ë„¤íŠ¸ì›Œí¬ ì ‘ê·¼ ì œì–´ ì†”ë£¨ì…˜ ê´€ë¦¬ì ì½˜ì†” ë§ˆì´ê·¸ë ˆì´ì…˜ ê²½í—˜ (JQuery â†’ ExtJS)
  - ê´‘ê³  í”Œë«í¼ ì‚¬ì´íŠ¸ ê³ ë„í™” ë° ë§ˆì´ê·¸ë ˆì´ì…˜ (JQuery â†’ React)

  `í˜‘ì—… ëŠ¥ë ¥ì´ ì €ì˜ ì œì¼ í° ì¥ì  ì…ë‹ˆë‹¤.`

  - ì¢‹ì€ ê°œë°œ ë¬¸í™”ë¥¼ ë§Œë“œëŠ”ë° ì•ì¥ì„œë©° ê´€ë¦¬ ë° í˜‘ì—… ë„êµ¬ë¥¼ ì˜ ì“°ê³ ì‹¶ì–´í•©ë‹ˆë‹¤.
  - JIRA Sprint ë¦¬ë” ê²½í—˜ì´ ìˆìœ¼ë©° Wiki ë¬¸ì„œ ì‘ì„±í•˜ê³  `ì¢‹ì•„ìš” ğŸ‘ğŸ»` ë°›ëŠ” ê²ƒì„ ì¢‹ì•„í•©ë‹ˆë‹¤.
  - Gitì„ ììœ ìì œë¡œ ì‚¬ìš©í•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.

  `ë™ë£Œë“¤ë„ ì €ì˜ ê³ ê°ì…ë‹ˆë‹¤.`

  - ì €ì™€ ë™ë£Œë“¤ ëª¨ë‘ê°€ ê°œë°œí•˜ëŠ”ë° ì§‘ì¤‘í•  ìˆ˜ ìˆëŠ” í™˜ê²½ì„ ë§Œë“œëŠ” ê²ƒì€ ì €ì˜ ê³ ë¯¼ ê±°ë¦¬ ì¤‘ í•˜ë‚˜ ì…ë‹ˆë‹¤.
  - íš¨ìœ¨ì ìœ¼ë¡œ ì¼í•˜ê³  ì‹¶ìŠµë‹ˆë‹¤.
  - ë•Œë¬¸ì— DevOpsì— ê´€ì‹¬ì´ ë§ìŠµë‹ˆë‹¤.

  ì£¼ìš” ê´€ì‹¬ íŒŒíŠ¸ : <mark>Front-End</mark> , <mark>Back-End</mark>

content:
  - title: Skill
    layout: skill
    first-card: markdown
    quote: >
      í˜„ì¬ ì—…ë¬´ì— ì‚¬ìš© ì¤‘ì´ê±°ë‚˜ í˜¹ì€ ì‚¬ìš©í–ˆë˜ ê¸°ìˆ  í˜¹ì€ ë„êµ¬ë“¤ì…ë‹ˆë‹¤.
    content:
      - layout: left
        title: Front-End
        card: markdown
        description: |
          - HTML, CSS, JavaScript, TypeScript
          - React, Redux, Redux-Saga, React-query, Next.JS
          - styled components, emotion, Material-UI
          - Sencha, jQuery, Sass
          - npm, yarn, yarn berry
          - ESLint, Prettier
      - layout: left
        title: Back-End
        card: markdown
        description: |
          - NodeJS, Express, NginX, Apache2
          - PHP
          - MySQL, MariaDB, Oracle, MS SQL, Redis
          - Swagger
      - layout: left
        title: DevOps
        card: markdown
        description: |
          - AWS, GCP
          - Git, Make, Gradle, GNU Bash Script, Docker
          - Bamboo, Jenkins
          - AWS CDK, Terraform
          - Vagrant, Chef
      - layout: left
        title: Etc
        card: markdown
        description: |
          - C, C++, Python
          - Robot Framework, Autoit

  - title: Project
    layout: list
    content:
      - layout: top-middle
        quote: >
          ì•„ë˜ëŠ” ì£¼ìš” í”„ë¡œì íŠ¸ ì…ë‹ˆë‹¤.
      - layout: left
        sub_title: ë§ˆì´ë°ì´í„° Front-End mobile WebView ì„œë¹„ìŠ¤ ê°œë°œ
        caption: 11ë²ˆê°€<br />21.08 ~ 22.11
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - 11ë²ˆê°€ê°€ ë§ˆì´ë°ì´í„° ì‚¬ì—…ìë¡œ ì°¸ì—¬í•¨ì— ë”°ë¼ ê³ ê°ì—ê²Œ ì‹ ìš© ì •ë³´ë¥¼ ê¸°ë°˜ìœ¼ë¡œ ë°ì´í„°ë¥¼ ì œê³µ

          <strong>â ì—­í• </strong>
            - ë¨¸ë‹ˆí•œì”(ë§ˆì´ë°ì´í„°) FE ì„œë¹„ìŠ¤ ì‹ ê·œ ê°œë°œ
            - ë§ˆì´ë°ì´í„° í™ˆí˜ì´ì§€ FE ì‹ ê·œ ê°œë°œ
            - ë§ˆì´ë°ì´í„° Back Office ì‹ ê·œ ê°œë°œ
            - Storybookì„ í†µí•œ ë””ìì¸ ì‹œìŠ¤í…œ êµ¬ì¶•
            - ë§ˆì´ë°ì´í„° íšŒì› - 11ë²ˆê°€ íšŒì› ì—°ë™
            - 11ë²ˆê°€ Appì—ì„œ ì œê³µí•˜ëŠ” Scheme ì—°ë™
            - ì‚¬ìš©ì ì •ë³´ì œê³µë™ì˜ ì‹œ ê³µë™ì¸ì¦ì„œ, ì‚¬ì„¤ì¸ì¦ì„œ ì—°ë™
            - ì•± ìœ„ë³€ì¡° ì†”ë£¨ì…˜ ì ìš©
            - FE ëª¨ë…¸ë ˆí¬ êµ¬ì„±, PnP ì ìš©
            - Client Logging êµ¬ì„±

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
          - TypeScript, React, Next.js
          - Storybook, Emotion
          - Recoil, React-Query
          - Jest, Cypress
          - AWS CloudFront, EC2, ELB, Nginx
          - Sentry
          - Yarn berry, Mono Repo

          <strong>â ì„±ê³¼</strong>
            - ë§ˆì´ë°ì´í„° ì„œë¹„ìŠ¤ ì˜¤í”ˆ(22.10.24, <a href="https://news.mt.co.kr/mtview.php?no=2022102508162794435">ë‰´ìŠ¤ ê¸°ì‚¬</a>)

      - layout: left
        sub_title: ê´‘ê³  í”Œë«í¼ ì›¹ ì‚¬ì´íŠ¸ ê°œë°œ<br />(Front-End)
        caption: Motov<br />20.09 ~ 21.07
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
        #   - title: Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title: Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - ê´‘ê³  í”Œë«í¼ì„ ë²„ì „ 2.0ì—ì„œ 3.0 ê°œë°œì„ ì§„í–‰í•˜ë©´ì„œ í”Œë«í¼ ìì²´ë¥¼ ìƒˆë¡­ê²Œ ê°œë°œí•˜ì—¬ ê³ ë„í™”í•˜ëŠ” í”„ë¡œì íŠ¸
            - TTD(Taxi Top Driver)ë¼ê³  ë¶ˆë¦¬ëŠ” íƒì‹œ ìƒë‹¨ì— ì˜¬ë¼ê°€ëŠ” ë””ìŠ¤í”Œë ˆì´ì—ì„œ ì†¡ì¶œí•  ê´‘ê³ ë¥¼ ê´€ë¦¬í•˜ëŠ” ì‚¬ì´íŠ¸ ê°œë°œ
            - <a href="https://github.com/InteractiveAdvertisingBureau/OpenDirect">OpenDirect</a> ê·œê²©ì— ë”°ë¥¸ ì‚¬ì´íŠ¸ ê°œë°œ

          <strong>â ì—­í• </strong>
            - ê´‘ê³ ì£¼ë“¤ì´ ê´‘ê³ ë¥¼ ê´€ë¦¬í•  ìˆ˜ ìˆëŠ” 'ê´‘ê³ ì£¼ ì‚¬ì´íŠ¸' Front-End ê°œë°œ
            - Zeplinì„ í†µí•œ ë””ìì´ë„ˆì™€ ì†Œí†µì„ í†µí•œ UX ë””ìì¸ ì°¸ì—¬
            - 'ê´‘ê³ ì£¼ ì‚¬ì´íŠ¸' Front-End ë¹Œë“œ ë° ë°°í¬
            - ìƒíƒœ ê´€ë¦¬ ë¼ì´ë¸ŒëŸ¬ë¦¬ ë³€ê²½ (Redux -> Recoil)

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - HTML, CSS, JavaScript, TypeScript
            - React, Recoil, Redux, Redux-Saga
            - Styled Component, Material UI
            - NodeJS, Express
            - ESLint, Prettier

          <strong>â ì„±ê³¼</strong>
            - ê´‘ê³ ì£¼ ê´‘ê³  ì‚¬ì´íŠ¸ ì´ˆê¸° ë‹¨ê³„ë¶€í„° ì„¤ê³„ ë° ê°œë°œ

      - layout: left
        sub_title: ê´‘ê³  í”Œë«í¼ CI/CD êµ¬ì¶•<br />(DevOps)
        caption: Motov<br />20.09 ~ 21.07
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - ì„œë¹„ìŠ¤ë“¤ì˜ ë¹Œë“œ ë° ë°°í¬ ìë™í™” êµ¬ì¶•
            - ë°ì´í„°ë² ì´ìŠ¤ ë§ˆì´ê·¸ë ˆì´ì…˜ ê´€ë¦¬ ì²´ê³„ êµ¬ì¶•

          <strong>â ì—­í• </strong>
            - ì„œë¹„ìŠ¤ ë²„ì „ ì—…ë°ì´íŠ¸ ì²´ê³„ êµ¬ì¶• ë° ìë™í™”
            - ì‚¬ë‚´ Git flow ì •ì˜
            - ê¸°ì¡´ì˜ CI/CD ì„œë²„ì—ì„œ ë§ˆì´ê·¸ë ˆì´ì…˜ (Jenkins â¡ AWS CodePipeline)
            - ì„œë¹„ìŠ¤ í™˜ê²½ ë³„ ë¹Œë“œ ë° ë°°í¬ í”„ë¡œì„¸ìŠ¤ Pipelineí™” (AWS CodePipeline, AWS CodeBuild, AWS CodeDeploy)
            - AWS RDS(Aurora) ë§ˆì´ê·¸ë ˆì´ì…˜ ìë™í™” êµ¬ì¶• (flyway)
            - Blue/Green ë¬´ì¤‘ë‹¨ ë°°í¬ (Nginx, Docker)
            - JIRA ì´ìŠˆ ìŠ¤í”„ë¦°íŠ¸ ë¦¬ë”
            - AWS CDKë¥¼ ì´ìš©í•œ IoCí™” ì§„í–‰

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - Jira, Confluence, Bitbucket
            - Git, NPM, Yarn, Gradle, Bash, Docker
            - Jenkins, Nginx, Slacek WEB API, Flyway
            - AWS CodePipeline, CodeBuild, CodeDeploy

          <strong>â ì„±ê³¼</strong>
            - ê´‘ê³  í”Œë«í¼ ì„œë¹„ìŠ¤ì˜ Pipeline êµ¬ì¶•
            - ê´‘ê³  í”Œë«í¼ ì„œë¹„ìŠ¤ ë³„ë¡œ Pipeline IoCí™” ì™„ë£Œ (AWS CDK)
            - ê´‘ê³  í”Œë«í¼ ì„œë¹„ìŠ¤ ë³„ë¡œ Pipeline Event ì•Œë¦¼ Slack Botì„ IoCí™”

      - layout: left
        sub_title: ê´‘ê³  í”Œë«í¼ Cloud Architecture Design (DevOps)
        caption: Motov<br />20.09 ~ 21.07
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - ê´‘ê³ ì£¼ í”Œë«í¼ì˜ AWS Cloud Network Architecture ì„¤ê³„ ë° êµ¬ì¶•
            - IoC(Infrastructure as Code)ë¥¼ í†µí•œ í´ë¼ìš°ë“œ ê´€ë¦¬ë¥¼ ìœ„í•œ ê°œë°œ

          <strong>â ì—­í• </strong>
            - AWS Cloud Architecture ì„¤ê³„ ë° êµ¬ì¶•
            - AWS Session managerë¥¼ í†µí•˜ì—¬ ë³´ì•ˆ ì ‘ê·¼ ê°€ëŠ¥í•˜ë„ë¡ êµ¬ì¶•
            - ì´ˆê¸° IoCëŠ” Terraformìœ¼ë¡œ ì§„í–‰
            - ì¶”í›„ AWSì— Nativeí•œ CDKë¥¼ ì´ìš©í•œ IoC ì§„í–‰

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - AWS CDK, Terraform
            - AWS ë„¤íŠ¸ì›Œí¬ ê´€ë ¨ Resource
            - AWS Session Manager

          <strong>â ì„±ê³¼</strong>
            - ê´‘ê³  í”Œë«í¼ì˜ ì´ˆê¸° Network Architecture Design
            - ê´‘ê³  í”Œë«í¼ ì„œë¹„ìŠ¤ êµ¬ì¡°ì˜ ë³´ì•ˆì„±ì„ ë†’ì´ë©´ì„œ Cloud Computingì— ë³´ë‹¤ ì‰½ê²Œ ì ‘ê·¼ í•  ìˆ˜ ìˆë„ë¡ ì„¤ê³„

      - layout: left
        sub_title: NAC ê´€ë¦¬ì ì›¹ ì„œë¹„ìŠ¤ ê°œë°œ<br />(Front-End / DevOps)
        caption: NetMan<br />18.01 ~ 19.05
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - ì›¹ ì„œë¹„ìŠ¤ ê¸°ë°˜ OS í˜•íƒœì˜ ë„¤íŠ¸ì›Œí¬ ê´€ë¦¬ì ì½˜ì†” ê°œë°œ
            - ê¸°ì¡´ì˜ Window ê¸°ë°˜ì˜ ë„¤íŠ¸ì›Œí¬ ê´€ë¦¬ì ì½˜ì†”ì€ ë°°í¬ì™€ ìˆ˜ì •ì´ ì–´ë ¤ì›€ ë°œìƒ
            - Spring Cloud ë„ì…

          <strong>â ì—­í• </strong>
            - web frontend ê°œë°œ
            - API ì„¤ê³„ ì°¸ì—¬ (swagger)
            - ê°œë°œ í™˜ê²½ êµ¬ì¶• ê°€ì´ë“œ ë¬¸ì„œ í†µí•© (confluence)
            - Git ë ˆí¬ì§€í† ë¦¬ ê´€ë¦¬ (ì„œë¸Œëª¨ë“ˆ êµ¬ì„± ê´€ë¦¬)
            - ì§€ì†ì ì¸ í†µí•© ë° ë°°í¬ ê°€ëŠ¥í•˜ë„ë¡ êµ¬ì„± ë° ê´€ë¦¬ (bamboo í”„ë¡œì íŠ¸ êµ¬ì„± ë° ìŠ¤í¬ë¦½íŠ¸ ê°œë°œ)
            - MFC/C#ìœ¼ë¡œ ê°œë°œëœ ê¸°ì¡´ì˜ ë„¤íŠ¸ì›Œí¬ ê´€ë¦¬ ì• í”Œë¦¬ì¼€ì´ì…˜ì„ ì›¹ ì„œë¹„ìŠ¤ ì•±ìœ¼ë¡œ ë§ˆì´ê·¸ë ˆì´ì…˜(ë˜ëŠ” ì‹ ê·œ ê°œë°œ)
            - ë¹Œë“œ ë° ë°°í¬ ìë™í™” êµ¬ì¶• (bamboo)

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - HTML, CSS, Sass, JavaScript, Sencha ExtJS6, jQuery, ESLint, Prettier
            - Git Submodule, Swagger, Confluence, Bamboo, Chef

          <strong>â ì„±ê³¼</strong>
            - ì›¹ ì„œë¹„ìŠ¤ ì•± (ëŒ€ì‹œë³´ë“œ, ë„¤íŠ¸ì›Œí¬ ê´€ë¦¬, DHCP ê´€ë¦¬ ì•±) ê°œë°œ
            - CI / CD ë„ì…
            - Front End ì½”ë”© ìŠ¤íƒ€ì¼ í†µí•© (ESLint, GitHook)

      - layout: left
        sub_title: Manager Server Team CI/CD í”„ë¡œì„¸ìŠ¤ ê°œì„  ë° ê´€ë¦¬<br />(DevOps)
        caption: NetMan<br />19.01 ~ 20.09
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš” / ëª©í‘œ</strong>
            - ë¹Œë“œ, íŒ¨í‚¤ì§€, í…ŒìŠ¤íŠ¸ ë° ë°°í¬ í”„ë¡œì„¸ìŠ¤ ê°œí¸ ë° ê´€ë¦¬
            - ì„œë²„ ì¥ë¹„ì— íƒ‘ì¬ë  ì†Œí”„íŠ¸ì›¨ì–´ ì„¤ì¹˜ íŒ¨í‚¤ì§€ ê°œì„ 
            - ì„¤ì¹˜ íŒ¨í‚¤ì§€ì˜ ì‹ ë¢°ì„± í™•ë³´ (ê¸°ì¡´ Bash Scriptë¡œ ì œì‘ëœ íŒ¨í‚¤ì§€ì˜ ì˜ˆì™¸ ì²˜ë¦¬ ë¶€ì¡±ìœ¼ë¡œ ì¸í•œ ì‹ ë¢°ì„± ë¶€ì¡±)
            - í˜•ìƒ ê´€ë¦¬ ë„êµ¬ì™€ CI/CD ì„œë²„ êµ¬ì¶•ì„ í†µí•œ ìë™í™” í”„ë¡œì„¸ìŠ¤ ë„ì…

          <strong>â ì—­í• </strong>
            - makeì™€ bash Scriptë¥¼ í†µí•˜ì—¬ ì„œë¹„ìŠ¤ ë¹Œë“œ ê°œì„ 
            - Docker Image ì œì‘ì„ í†µí•˜ì—¬ ë¹Œë“œ ë° ê°œë°œ í™˜ê²½ í†µí•©
            - í˜•ìƒ ê´€ë¦¬ ë„êµ¬ ì‚¬ìš© (Chef)ì„ í†µí•œ íŒ¨í‚¤ì§€ ì‹ ë¢°ë„ ê°œì„ 
            - ê°€ìƒë¨¸ì‹ ì„ ë³´ë‹¤ ì‰½ê²Œ ê´€ë¦¬ í•  ìˆ˜ ìˆëŠ” Vagrantì™€ ìŠ¤í¬ë¦½íŠ¸ ì‘ì„±ìœ¼ë¡œ ìë™í™” í…ŒìŠ¤íŒ… í™˜ê²½ êµ¬ì¶•
            - ì§€ì†ì ì¸ í†µí•© ë° ë°°í¬ ë„êµ¬(Bamboo) ë„ì…ìœ¼ë¡œ CI/CD ì„œë²„ êµ¬ì¶•

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - Git, Swagger, Confluence, Bamboo
            - Docker, make, Chef, Vagrant, Bash

          <strong>â ì„±ê³¼</strong>
            - ê¸°ì¡´ë³´ë‹¤ ì¦ì€ íœ´ë¨¼ ì—ëŸ¬ë¥¼ ì œê±°
            - C/C++ ì„œë¹„ìŠ¤ ë¹Œë“œ ìë™í™” ë„ì…
            - íŒ¨í‚¤ì§€ ì œì‘ ìë™í™” ë„ì…, ì œì‘ ì‹œê°„ ë‹¨ì¶•, ì„¤ì¹˜ í…ŒìŠ¤íŠ¸ ìë™í™”
            - ì„¤ì¹˜ íŒ¨í‚¤ì§€ì˜ ì‹ ë¢°ì„±ì„ ë†’ì´ê³  ë¹„ì§€ë‹ˆìŠ¤ ê°œë°œì— ì§‘ì¤‘ í•  ìˆ˜ ìˆë„ë¡ CI/CD ì„œë²„ ë„ì…
            - Git Flow ë„ì…ìœ¼ë¡œ í˜‘ì—… í™˜ê²½ ê°œì„ 
            - ê°œë°œ í™˜ê²½ í†µí•©

      - layout: left
        sub_title: ë„¤íŠ¸ì›Œí¬ ì¸ì¦ ë° ìì‚° ì‹ ì²­ ì„œë¹„ìŠ¤<br />ê´€ë¦¬ì ì„¤ì • ì„œë¹„ìŠ¤<br />ê°œë°œ ë° ìœ ì§€ë³´ìˆ˜<br />(Full Stack)
        caption: NetMan<br />19.01 ~ 20.09
        description: |
          <strong>â í”„ë¡œì íŠ¸ ê°œìš”</strong>
            - ì›¹ ì„œë¹„ìŠ¤ ê¸°ë°˜ì˜ ë„¤íŠ¸ì›Œí¬ ê´€ë¦¬ì ì½˜ì†”(ì„¤ì •/ê´€ë¦¬ ê¸°ëŠ¥) ê°œë°œ ë° ìœ ì§€ë³´ìˆ˜ë¥¼ ë‹´ë‹¹

          <strong>â ì—­í• </strong>
            - ì›¹ ì„œë¹„ìŠ¤ ê°œë°œ ë° ìœ ì§€ë³´ìˆ˜ (Apache2, PHP, MySQL, JavaScript, Jquery, JQ Widget)

          <strong>â ì‚¬ìš© ê¸°ìˆ </strong>
            - Apache2, PHP, MySQL
            - HTML, CSS, JavaScript, jQuery, JQ Widget

          <strong>â ì„±ê³¼</strong>
            - PHP 7 ë²„ì „ ì—…ê·¸ë ˆì´ë“œì— ë”°ë¥¸ ì†ŒìŠ¤ ë§ˆì´ê·¸ë ˆì´ì…˜
            - ê¸°ì¡´ì˜ HTML, PHP, JavaScriptê°€ ê°™ì´ ì“°ì˜€ë˜ ì†ŒìŠ¤ë¥¼ MVC íŒ¨í„´ì„ ê¸°ë°˜ìœ¼ë¡œ ë¶„ë¦¬í•˜ì—¬ ê°œì„ 
            - PHP ê¸°ë°˜ì˜ Restful APIë¡œ ë³€í™˜í•˜ì—¬ ì¬ì‚¬ìš©ì„±ê³¼ í™•ì¥ì„± ë§ˆë ¨

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Coupang
        sub_title: Rocket Growth<br />Front-End Engineer
        caption: 22.11 ~ í˜„ì¬
        # description: |
        #   * 1

      - layout: left
        title: 11ë²ˆê°€
        sub_title: SK Payment ë°ì´í„°íŒ€<br />Front-End Engineer
        caption: 21.08 ~ 22.11
        description: |
          * SK Payment ë§ˆì´ë°ì´í„° Front-End ì„œë¹„ìŠ¤ ê°œë°œ
          * SK Payment ë§ˆì´ë°ì´í„° ë””ìì¸ ì‹œìŠ¤í…œ êµ¬ì¶•
          * 22' SKT ì£¼ë‹ˆì–´ë³´ë“œ í™œë™ (22.01 ~ 22.12)
            * SK ê³„ì—´ì‚¬(ICT Family) ã…‡ê°€ã…‡ ì œí’ˆ Mobile APP UX ê°œì„ 

      - layout: left
        title: Motov
        sub_title: ê´‘ê³  í”Œë«í¼ ê°œë°œíŒ€<br />Front-End/DevOps Engineer
        caption: 20.09 ~ 21.07
        description: |
          * ê´‘ê³  í”Œë«í¼ì˜ Web ì‚¬ì´íŠ¸ ê°œë°œ (Front-End)
          * ê´‘ê³  í”Œë«í¼ì˜ CI/CD êµ¬ì¶• (DevOps)
          * ê´‘ê³  í”Œë«í¼ì˜ Cloud Architecture ì„¤ê³„ ë° IoC ê°œë°œ (DevOps)
          * AWS Cloud ê´€ë¦¬ì
          * ì‚¬ë‚´ ì„¸ë¯¸ë‚˜ í™œë™ ë° ì™¸ë¶€ í™œë™
            * AWS StartUp Teamê³¼ ì†Œí†µí•˜ì—¬ ì§€ì†ì ì¸ Cloud ì•„í‚¤í…ì³ ê°œì„  (20.09 ~)
            * AWS Network ì•„í‚¤í…ì²˜ êµ¬ì„± ë° ì„¸ë¯¸ë‚˜ (21.02.15)
            * ê´‘ê³  í”Œë«í¼ ì•„í‚¤í…ì³ êµ¬ì„± ë° ë°°í¬ (21.02.17)
            * AWS IAM ê³„ì • ì‚¬ìš© ì •ì±… ì„¸ë¯¸ë‚˜ (21.03.30) (<a href="https://minemanemo.tistory.com/140">í¬ìŠ¤íŒ… ë°”ë¡œê°€ê¸°</a>)
            * AWS Session Managerë¥¼ ì´ìš©í•œ ë³´ì•ˆ ì ‘ì† ë°©ë²• ì„¸ë¯¸ë‚˜ (21.03.30)
            * ì‹ ê·œ CI/CD í”„ë¡œì„¸ìŠ¤ ì„¸ë¯¸ë‚˜ (21.04.12)

      - layout: left
        title: NetMan
        sub_title: Manager Server íŒ€<br />WEB/DevOps Enginner
        caption: 18.01 ~ 20.09
        description: |
          * ë„¤íŠ¸ì›Œí¬ ì ‘ê·¼ ì œì–´ ì†”ë£¨ì…˜(NAC)ì˜ ê´€ë¦¬ ì„œë²„íŒ€ì—ì„œ ê·¼ë¬´
          * Webê¸°ë°˜ OS í˜•íƒœì˜ ë„¤íŠ¸ì›Œí¬ ë§¤ë‹ˆì € ì„œë¹„ìŠ¤ ì‹ ê·œ ê°œë°œ (Front-End, DevOps)
          * íŒ€ì˜ ì „ë°˜ì ì¸ CI/CD Process ê°œí¸ ë° ìë™í™” ì ìš©
          * PHP ê¸°ë°˜ì˜ WEB ì„œë¹„ìŠ¤ ê°œë°œ ë° ìœ ì§€ë³´ìˆ˜
          * C++ ê¸°ë°˜ì˜ Linux App/ì„œë¹„ìŠ¤ ê°œë°œ ë° ìœ ì§€ë³´ìˆ˜
          * Atlassianì˜ Software ê´€ë¦¬ì (JIRA, Confluence, Bambbo)
          * ì—°êµ¬ì†Œì— ì‚¬ë‚´ ë©”ì‹ ì € ë„ì…(KakaoTalk â†’ HipChat â†’ Slack â†’ MS Teams)
          * 2018.10 ìš°ìˆ˜ ì‚¬ì› ì„ ì • (<a href="https://blog.naver.com/netman02/221390240278">ë¸”ë¡œê·¸ í¬ìŠ¤íŒ… ë°”ë¡œê°€ê¸°</a>)

      - layout: left
        title: NetMan
        sub_title: ì¸í„´ì‹­
        caption: 17.03 ~ 17.09 (FullTime)<br />17.09 ~ 17.12 (PartTime)
        description: |
          * ICT ì¸í„´ì‹­ í”„ë¡œê·¸ë¨ì„ í†µí•œ ì¸í„´ì‹­ í™œë™ (FullTime)
          * ICT ì¸í„´ì‹­ ì¢…ë£Œ í›„ í•™êµ ìˆ˜ì—…ê³¼ íšŒì‚¬ë¥¼ ë³‘í–‰ (PartTime)
          * ê°ì¢… ì„œë¹„ìŠ¤ì˜ í…ŒìŠ¤íŒ…ì„ ìœ„í•œ Tool ë° í…ŒìŠ¤íŒ… ìë™í™” êµ¬ì¶•
            * Pythonì„ ì´ìš©í•œ C êµ¬ì¡°ì²´ ì»¤ìŠ¤í…€ íŒ¨í‚· ë°œìƒê¸° ì œì‘ (17.03 ~ 17.05)
            * Robot Frameworkë¥¼ ì´ìš©í•œ Windows ë‹¨ë§ í…ŒìŠ¤íŒ… ìë™í™” (17.05 ~ 17.07)
            * Vagrantë¥¼ ì´ìš©í•œ Windows OS ë‹¨ë§ ì›ê²© í…ŒìŠ¤íŒ… ìë™í™” (17.08 ~ 17.12)

  - title: Resource
    layout: list
    content:
      - layout: left
        title: ê°œì¸ ë¸”ë¡œê·¸
        sub_title: https://minemanemo.tistory.com
        description: |
          * ê°œì¸ ê¸°ìˆ  ë¸”ë¡œê·¸ ì…ë‹ˆë‹¤.
          * ì—…ë¬´ ì¤‘ ë°œìƒí•œ íŠ¸ëŸ¬ë¸” ìŠˆíŒ… ë‚´ìš©, ìƒˆë¡­ê²Œ ê³µë¶€í•œ ë‚´ìš© ë“± ê°œë°œì— ê´€ë ¨ëœ ë‚´ìš©ì„ ì£¼ì œë¡œ í¬ìŠ¤íŒ… í•©ë‹ˆë‹¤.
          * ì‚¬ë‚´ Wikiì— ì ì€ ê¸€ ì¤‘ì—ì„œ ê³µìœ í•˜ë©´ ì¢‹ì„ ê²ƒ ê°™ì€ ë‚´ìš©ì€ ì˜®ê¸°ê¸°ë„ í•©ë‹ˆë‹¤.
          * ìµœëŒ€í•œ ë¨¸ë¦¬ê°€ ì•„ë‹Œ ê¸€ë¡œ ê¸°ì–µí•˜ë ¤ê³  ë…¸ë ¥í•©ë‹ˆë‹¤.
          * ì£¼ì¤‘ ì¼ í‰ê·  150ëª… ë°©ë¬¸ì ë¸”ë¡œê·¸ ì…ë‹ˆë‹¤.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    'Gemfile',
    'Gemfile.lock',
    'node_modules',
    'vendor/bundle/',
    'vendor/cache/',
    'vendor/gems/',
    'vendor/ruby/',
    'lib/',
    'scripts/',
  ]
